# ____       _   _            _____ _                 _                       ____
#|  _ \     | | | |          / ____| |               (_)                     |___ \
#| |_) | ___| |_| |_ ___ _ _| (___ | | ___  ___ _ __  _ _ __   __ _     __   ____) |
#|  _ < / _ \ __| __/ _ \ '__\___ \| |/ _ \/ _ \ '_ \| | '_ \ / _` |    \ \ / /__ <
#| |_) |  __/ |_| ||  __/ |  ____) | |  __/  __/ |_) | | | | | (_| |     \ V /___) |
#|____/ \___|\__|\__\___|_| |_____/|_|\___|\___| .__/|_|_| |_|\__, |      \_/|____/
#                                              | |             __/ |
#                                              |_|            |___/


# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Useful links:
# Our Spigot plugin page:                                       https://www.spigotmc.org/resources/bettersleeping-1-12-1-14.60837/
# For support or suggestions, head over to our Discord server:  https://discord.gg/AS46VGT
# You can find a live list of upcoming features/bug fixes here: https://github.com/Nuytemans-Dieter/BetterSleeping/issues
# The progress of the next release can be found here:           https://github.com/Nuytemans-Dieter/BetterSleeping/milestones
# Considered buying the premium version? (Spigot account needed)https://www.spigotmc.org/resources/bettersleeping-premium-1-13-1-16.78951/

# Configuration guide and default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/config.yml
# All default config files can be found here:   https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources

# The default language file to be used
# Options: en-US (English), nl-BE (Dutch), es-ES (Spanish), pt-PT (Portuguese), de-DE.yml (German), fr-FR (French), Chinese (zh-ZH)
# Want to disable all messages? Set this to: "silent". It will load an empty config files and will disable most messages
# Up-to-date list here: https://github.com/Nuytemans-Dieter/BetterSleeping/tree/v3.0.0/src/main/resources/lang
language: "en-US"

# Choose whether to use the short prefix: [BS] (true) or the long one [BetterSleeping] (false)
shorten_prefix: true

# Choose where messages show up
# Messages are shown in the chat when set to false, and shown in the action bar when set to true
action_bar_messages: false

# This is ran once on startup when enabled to fetch the latest version
update_notifier: true

# Whether or not phantoms should be disabled
disable_phantoms: false

# Automagically add all missing options in your config (when you delete an option or an update has new features)
# IMPORTANT NOTE: This will reset all comments above options, except for a link to the documentation
# Options in this file will never be automatically added due to the importance of some information
auto_add_missing_options: false