#
# ____       _   _            ____  _                    _                       _  _
#| __ )  ___| |_| |_ ___ _ __/ ___|| |    ___  ___ _ __ (_)_ __   __ _    __   _| || |
#|  _ \ / _ \ __| __/ _ \ '__\___ \| |   / _ \/ _ \ '_ \| | '_ \ / _` |   \ \ / / || |_
#| |_) |  __/ |_| ||  __/ |   ___) | |__|  __/  __/ |_) | | | | | (_| |    \ V /|__   _|
#|____/ \___|\__|\__\___|_|  |____/|_____\___|\___| .__/|_|_| |_|\__, |     \_/    |_|
#                                                 |_|            |___/



# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Useful links:
# Our Spigot plugin page:                                       https://www.spigotmc.org/resources/bettersleeping-1-12-1-14.60837/
# For support or suggestions, head over to our Discord server:  https://discord.gg/AS46VGT
# You can find a live list of upcoming features/bug fixes here: https://github.com/Nuytemans-Dieter/BetterSleeping/issues
# The progress of the next release can be found here:           https://github.com/Nuytemans-Dieter/BetterSleeping/milestones
# Considered buying the premium version? (Spigot account needed)https://www.spigotmc.org/resources/bettersleeping-premium-1-13-1-16.78951/

# Default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/BetterSleeping-v4/src/main/resources/config.yml
# Config template:      https://github.com/Nuytemans-Dieter/BetterSleeping/blob/BetterSleeping-v4/src/main/resources/templates/config.yml
# All default config files can be found here:  https://github.com/Nuytemans-Dieter/BetterSleeping/tree/BetterSleeping-v4/src/main/resources

# After changing this option, please delete 'lang.yml' and do /bs reload or restart your server
# The default language file to be used
# Options: en-US (English), nl-BE (Dutch), es-ES (Spanish), pt-PT (Portuguese), de-DE.yml (German), fr-FR (French), Chinese (zh-ZH)
# Want to disable all messages? Set this to: "silent". It will load an empty config files and will disable most messages
# Up-to-date list here: https://github.com/Nuytemans-Dieter/BetterSleeping/tree/BetterSleeping-v4/src/main/resources/lang
language: {language}

# Choose where messages show up
# Messages are shown in the chat when set to false, and shown in the action bar when set to true
# This will ONLY work if you are using Spigot
action_bar_messages: {action_bar_messages}

# Use the bossbar to display the amount of sleeping players
enable_bossbar: {enable_bossbar}

# This is ran once on startup when enabled to fetch the latest version
update_notifier: {update_notifier}

# Whether or not phantoms should be disabled
disable_phantoms: {disable_phantoms}

# Whether you want to show particle animations when players are sleeping
# These are precomputed to save on processing time
enable_animations: {enable_animations}

# Whether you want to save BetterSleeping output to log files
save_logs: {save_logs}