#
# ____       _   _            ____  _                    _                       _  _
#| __ )  ___| |_| |_ ___ _ __/ ___|| |    ___  ___ _ __ (_)_ __   __ _    __   _| || |
#|  _ \ / _ \ __| __/ _ \ '__\___ \| |   / _ \/ _ \ '_ \| | '_ \ / _` |   \ \ / / || |_
#| |_) |  __/ |_| ||  __/ |   ___) | |__|  __/  __/ |_) | | | | | (_| |    \ V /|__   _|
#|____/ \___|\__|\__\___|_|  |____/|_____\___|\___| .__/|_|_| |_|\__, |     \_/    |_|
#                                                 |_|            |___/


# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/BetterSleeping-v4/src/main/resources/sleeping_settings.yml
# Config template:      https://github.com/Nuytemans-Dieter/BetterSleeping/blob/BetterSleeping-v4/src/main/resources/templates/sleeping_settings.yml
# All default config files can be found here:  https://github.com/Nuytemans-Dieter/BetterSleeping/tree/BetterSleeping-v4/src/main/resources

# Choose an option from below (percentage or absolute)
# With percentage, a relative amount of players needs to sleep (eg. needed: 30 -> 13 online players, 30% of 13 is 3,9. Will be rounded to the nearest number -> 4 sleeping players needed)
# With absolute, a static amount of players needs to sleep (eg. needed: 2 -> any amount of online players, 2 players need to sleep)
sleeper_calculator: {sleeper_counter}

# This depends on your sleeper_calculator setting
#     Percentage: This value is the percentage of players in a world that must sleep ([0, 100])
#     Absolute: This value is always the amount of players that must sleep, does not scale with the amount of online players!
needed: {needed}

# The duration (in seconds) of the night when enough players are sleeping
# Set this to 0 to skip the night instantly
# A normal night lasts 500 seconds
night_skip_length: {night_skip_length}

# The normal length of the day and night when not skipping (in seconds)
# This allows you to speed up or slow down the time
# Default: 700
day_length: {day_length}
# Default: 500
night_length: {night_length}


# The time in seconds that players need to wait before they can enter the bed again after leaving it
bed_enter_cooldown: {bed_enter_delay}

# Disable BetterSleeping in certain worlds. This option is case sensitive!
# Sleeping is always enabled in worlds that are not in this list